name: Reusable-workflow
on: 
  workflow_call:
    inputs:
      passvalue:
        description: passvalue from calling work low
        required: false
        type: string
        default: empty
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy step is now ready
        run: echo "deploy steps are now ready ${{ inputs.passvalue }}"
      - name: deploy complete steps
        run: echo "deploy steps are completed"
