name: action typs
on:
  #pull_request:
  push:
    types:
      - opened
    branches:
      - main
    paths-ignore:
      - '.github/workflow/*'
  workflow_dispatch:
env:
  database_name: dhirendraxuz
jobs:
  job1:
    env:
      user_name:  job1Dps@xyz123
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: ls
      - name: get code from git hub to agent machine
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: message
          path: pushtest.txt
      - name: out put content
        run: |
          echo "${{ env.user_name }} and ${{ env.database_name }}" 
  job2:
    env:
      user_name: Job2@dhirendra
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: message
      - name: out put content
        run: |
          ls
          echo "${{ env.user_name }} and ${{ env.database_name }}" 
        
      
    
