name: wfpathfilter
on:
# push:
  pull_request:
    types: opened
    branches:
      - main
      - dev-*
      - features/**
    paths-ignore:
      - '.github/workflows/**'
      
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step one show greetings
        run: echo "hello world"
      
      
